version: 2
jobs:
  build:
    working_directory: /home/circleci/dockerized-rails-example
    parallelism: 2
    docker:
      - image: ruby:2.4.1
        environment:
          DATABASE_URL: postgres://postgres:@localhost
      - image: postgres:9.6
    steps:
      - run:
          name: Install System Dependencies
          command: apt-get update && apt-get install -y --no-install-recommends postgresql-client
      - checkout
      - restore_cache:
          keys:
            - dockerized-rails-example-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - dockerized-rails-example-{{ checksum "Gemfile.lock" }}
            - dockerized-rails-example-
      - run:
          name: Install Rails Dependencies
          command: |
            bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
            bundle clean
      - save_cache:
          key: dockerized-rails-example-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - save_cache:
          key: dockerized-rails-example-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Create DB
          command: |
            bundle exec rails db:create
      - run:
          name: RSpec
          command: |
            bundle exec rspec --profile 10 \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
